<?php
/**
 * Site footer.
 *
 * GENERATED by wordpress/build.sh from index.html. Edit that file and re-run
 * the script; changes made here are overwritten.
 *
 * @package captal-onepage
 */

if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'footer' ) ) :
	?>
<footer class="site-footer on-ink">
  <div class="wrap">
    <div class="site-footer__grid">
      <div class="site-footer__brand">
        <span class="logo logo--cream" style="font-size:16px">CAP<span class="logo__bars" aria-hidden="true"><i></i><i></i></span>TAL</span>
        <p class="site-footer__blurb">
          Financial excellence, quietly executed. Performance visibility for
          companies built to be held.
        </p>
      </div>

      <div class="site-footer__col">
        <div class="site-footer__heading">What we engage</div>
        <ul class="site-footer__links">
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Performance Visibility</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Financial Leadership</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Transactions</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Operational Finance</a></li>
        </ul>
      </div>

      <div class="site-footer__col">
        <div class="site-footer__heading">The house</div>
        <ul class="site-footer__links">
          <li><a href="<?php echo esc_url( home_url( '/#philosophy' ) ); ?>">What we believe</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#learned' ) ); ?>">What we learned</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#cases' ) ); ?>">Cases</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#people' ) ); ?>">Who we are</a></li>
        </ul>
      </div>

      <div class="site-footer__col">
        <div class="site-footer__heading">Legal</div>
        <ul class="site-footer__links">
          <li><a href="#">Privacy</a></li>
          <li><a href="#">Terms of engagement</a></li>
          <li><a href="#">Regulatory disclosures</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__base">
      <div>&copy; MMXXVI Capiital &middot; Information on this site is provided for general informational purposes only and does not constitute investment, legal, tax or accounting advice.</div>
    </div>
  </div>
</footer>
<?php endif; ?>

<?php wp_footer(); ?>
</body>
</html>
