<?php
/**
 * Site footer.
 *
 * GENERATED by wordpress/build.sh from index.html. Edit that file and re-run
 * the script; changes made here are overwritten.
 *
 * @package captal-onepage
 */

if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'footer' ) ) :
	?>
<footer class="site-footer on-ink">
  <div class="container">
    <div class="grid-12 site-footer__grid">
      <div class="site-footer__brand">
        <span class="logo logo--cream"><span>CAP</span><span class="logo__equals" aria-hidden="true"></span><span>TAL</span></span>
        <p class="site-footer__blurb">
          Independent advisory counsel since 1994. Privately held. Conflict-free
          by design.
        </p>
      </div>

      <div class="site-footer__col">
        <div class="site-footer__heading">Practice</div>
        <ul class="site-footer__links">
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Mergers &amp; Acquisitions</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Capital Markets</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Restructuring</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Private Capital</a></li>
        </ul>
      </div>

      <div class="site-footer__col">
        <div class="site-footer__heading">Firm</div>
        <ul class="site-footer__links">
          <li><a href="<?php echo esc_url( home_url( '/#firm' ) ); ?>">About</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#firm' ) ); ?>">Partners</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#contact' ) ); ?>">Careers</a></li>
          <li><a href="<?php echo esc_url( home_url( '/#insights' ) ); ?>">Press</a></li>
        </ul>
      </div>

      <div class="site-footer__col">
        <div class="site-footer__heading">Legal</div>
        <ul class="site-footer__links">
          <li><a href="#">Privacy</a></li>
          <li><a href="#">Regulatory Disclosures</a></li>
          <li><a href="#">Modern Slavery Statement</a></li>
          <li><a href="#">Terms</a></li>
        </ul>
      </div>
    </div>

    <div class="site-footer__base">
      <div>&copy; 2026 CAP=TAL Partners LLP &middot; Authorised and regulated</div>
      <div>New York &middot; London &middot; Hong Kong &middot; Frankfurt &middot; Z&uuml;rich &middot; Singapore</div>
    </div>
  </div>
</footer>
<?php endif; ?>

<?php wp_footer(); ?>
</body>
</html>
