<?php
/**
 * Site header.
 *
 * GENERATED by wordpress/build.sh from index.html. Edit that file and re-run
 * the script; changes made here are overwritten.
 *
 * @package captal-onepage
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#242a33">
<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

<a class="skip-link" href="#content"><?php esc_html_e( 'Skip to content', 'captal-onepage' ); ?></a>

<?php
// Elementor Pro's Theme Builder header wins when one is published; otherwise
// the design's own header renders.
if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'header' ) ) :
	?>
<header class="site-header">
  <div class="site-header__inner">
    <a href="<?php echo esc_url( home_url( '/' ) ); ?>" aria-label="CAP=TAL — home">
      <span class="logo"><span>CAP</span><span class="logo__equals" aria-hidden="true"></span><span>TAL</span></span>
    </a>

    <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button>

    <nav class="site-nav" id="site-nav" aria-label="<?php esc_attr_e( 'Primary', 'captal-onepage' ); ?>">
    <?php
    if ( has_nav_menu( 'primary' ) ) :
    	wp_nav_menu(
    		array(
    			'theme_location' => 'primary',
    			'container'      => false,
    			'depth'          => 1,
    			'fallback_cb'    => false,
    		)
    	);
    else :
    	?>
      <a href="<?php echo esc_url( home_url( '/#firm' ) ); ?>">Firm</a>
      <a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">Advisory</a>
      <a href="<?php echo esc_url( home_url( '/#transactions' ) ); ?>">Transactions</a>
      <a href="<?php echo esc_url( home_url( '/#insights' ) ); ?>">Insights</a>
      <a href="<?php echo esc_url( home_url( '/#contact' ) ); ?>">Contact</a>
    	<?php
    endif;
    ?>
    </nav>

    <a class="link-rule link-rule--nav site-header__portal" href="<?php echo esc_url( home_url( '/#contact' ) ); ?>">Client Portal <span aria-hidden="true">&rarr;</span></a>
  </div>
</header>
<?php endif; ?>
