<?php
/**
 * Site header.
 *
 * GENERATED by wordpress/build.sh from index.html. Edit that file and re-run
 * the script; changes made here are overwritten.
 *
 * @package captal-onepage
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#242a33">
<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

<a class="skip-link" href="#content"><?php esc_html_e( 'Skip to content', 'captal-onepage' ); ?></a>

<?php
// Elementor Pro's Theme Builder header wins when one is published; otherwise
// the design's own header renders.
if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'header' ) ) :
	?>
<header class="site-header" data-scrolled="false">
  <div class="site-header__inner">
    <a class="site-header__home" href="<?php echo esc_url( home_url( '/#top' ) ); ?>" aria-label="Capiital — home">
      <span class="logo logo--current">CAP<span class="logo__bars" aria-hidden="true"><i></i><i></i></span>TAL</span>
    </a>

    <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu</button>

    <nav class="site-nav" id="site-nav" aria-label="<?php esc_attr_e( 'Primary', 'captal-onepage' ); ?>">
    <?php
    if ( has_nav_menu( 'primary' ) ) :
    	wp_nav_menu(
    		array(
    			'theme_location' => 'primary',
    			'container'      => false,
    			'depth'          => 1,
    			'fallback_cb'    => false,
    		)
    	);
    else :
    	?>
      <a href="<?php echo esc_url( home_url( '/#services' ) ); ?>">What we engage</a>
      <a href="<?php echo esc_url( home_url( '/#philosophy' ) ); ?>">What we believe</a>
      <a href="<?php echo esc_url( home_url( '/#learned' ) ); ?>">What we learned</a>
      <a href="<?php echo esc_url( home_url( '/#cases' ) ); ?>">Cases</a>
      <a href="<?php echo esc_url( home_url( '/#people' ) ); ?>">Who we are</a>
      <a href="<?php echo esc_url( home_url( '/#papers' ) ); ?>">What we think</a>
      <a href="<?php echo esc_url( home_url( '/#contact' ) ); ?>">How to reach us</a>
    	<?php
    endif;
    ?>
    </nav>
  </div>
  <div class="scroll-progress" aria-hidden="true"><div class="scroll-progress__bar"></div></div>
</header>
<?php endif; ?>
