<?php
/**
 * The CAP=TAL one-page layout: hero through offices.
 *
 * GENERATED by wordpress/build.sh from index.html. Edit that file and re-run
 * the script; changes made here are overwritten.
 *
 * The site header and footer are NOT here — they come from header.php and
 * footer.php so that ordinary pages and Elementor pages share the same chrome.
 *
 * @package captal-onepage
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!-- ── Hero ──────────────────────────────────────────────────────────────── -->
<section class="hero on-ink">
  <div class="container hero__body">
    <div class="eyebrow animate-rise">Independent &middot; Established 1994 &middot; Global</div>

    <h1 class="hero__title animate-rise delay-1">
      Counsel for the<br><span class="italic-accent">consequential</span>.
    </h1>

    <p class="hero__lede animate-rise delay-2">
      An independent advisory firm trusted by the world's leading corporations,
      sovereigns, and private capital institutions through their most defining
      transactions.
    </p>

    <div class="hero__actions animate-rise delay-3">
      <a class="btn-outline" href="#services">Our Practice <span aria-hidden="true">&rarr;</span></a>
      <a class="link-rule" href="#transactions">Selected Transactions</a>
    </div>
  </div>

  <div class="container hero__stats animate-rise delay-4">
    <div class="stat">
      <div class="stat__value">$420B+</div>
      <div class="stat__label">Aggregate transaction value</div>
    </div>
    <div class="stat">
      <div class="stat__value">1,200+</div>
      <div class="stat__label">Mandates completed</div>
    </div>
    <div class="stat">
      <div class="stat__value">32</div>
      <div class="stat__label">Countries served</div>
    </div>
    <div class="stat">
      <div class="stat__value">94%</div>
      <div class="stat__label">Repeat client engagement</div>
    </div>
  </div>
</section>

<!-- ── Client marquee ────────────────────────────────────────────────────── -->
<!-- The track holds the client list twice; the -50% keyframe lands exactly on
     the seam, so the loop is invisible. -->
<section class="marquee" aria-label="Selected clients">
  <div class="marquee__track animate-marquee">
    <div class="marquee__row">
      <span class="marquee__name">BERKHOLM &amp; CO.</span>
      <span class="marquee__name">ATRIA GROUP</span>
      <span class="marquee__name">MERIDIAN HOLDINGS</span>
      <span class="marquee__name">VALOREN INDUSTRIES</span>
      <span class="marquee__name">NORTHWICK CAPITAL</span>
      <span class="marquee__name">PORTUM ENERGY</span>
      <span class="marquee__name">KELVAR PHARMA</span>
      <span class="marquee__name">LUMEN SOVEREIGN</span>
    </div>
    <div class="marquee__row" aria-hidden="true">
      <span class="marquee__name">BERKHOLM &amp; CO.</span>
      <span class="marquee__name">ATRIA GROUP</span>
      <span class="marquee__name">MERIDIAN HOLDINGS</span>
      <span class="marquee__name">VALOREN INDUSTRIES</span>
      <span class="marquee__name">NORTHWICK CAPITAL</span>
      <span class="marquee__name">PORTUM ENERGY</span>
      <span class="marquee__name">KELVAR PHARMA</span>
      <span class="marquee__name">LUMEN SOVEREIGN</span>
    </div>
  </div>
</section>

<!-- ── § 01 The Firm ─────────────────────────────────────────────────────── -->
<section class="section" id="firm">
  <div class="container grid-12 firm__grid">
    <div class="firm__intro">
      <div class="eyebrow">&sect; 01 &mdash; The Firm</div>
      <h2 class="firm__title">An equation<br>of conviction<br><span class="italic-accent">and capital.</span></h2>
    </div>

    <div class="firm__prose">
      <p>
        Founded on a single principle: that disciplined judgment, free from
        conflict, compounds value across generations. We work exclusively in an
        advisory capacity &mdash; no proprietary balance sheet, no in-house funds,
        no competing interests.
      </p>
      <p>
        Our partners have advised on more than $420 billion of transactions
        across six continents, building enduring relationships with corporate
        boards, founding families, sovereigns, and the world's most discerning
        institutional investors.
      </p>

      <div class="hairline" style="margin-top:var(--space-12)"></div>

      <div class="firm__stats">
        <div class="stat stat--sm">
          <div class="stat__value">1994</div>
          <div class="stat__label">Founded</div>
        </div>
        <div class="stat stat--sm">
          <div class="stat__value">62</div>
          <div class="stat__label">Partners</div>
        </div>
        <div class="stat stat--sm">
          <div class="stat__value">9</div>
          <div class="stat__label">Global Offices</div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- ── § 02 Advisory Practice ────────────────────────────────────────────── -->
<section class="section on-ink" id="services">
  <div class="container">
    <div class="section-head">
      <div>
        <div class="eyebrow">&sect; 02 &mdash; Advisory Practice</div>
        <h2 class="section-head__title">Four disciplines.<br><span class="italic-accent">One standard.</span></h2>
      </div>
      <p class="section-head__aside">
        Integrated teams of sector and product specialists, deployed with the
        senior attention every mandate deserves.
      </p>
    </div>

    <div class="hairline-grid hairline-grid--on-ink hairline-grid--2">
      <div class="service-card">
        <div class="service-card__head">
          <span class="service-card__number">01</span>
          <span class="service-card__cue">Explore &rarr;</span>
        </div>
        <h3 class="service-card__title">Mergers &amp; Acquisitions</h3>
        <p class="service-card__body">
          Strategic advisory for sell-side, buy-side, and cross-border
          transactions. Trusted counsel through every stage of negotiation and
          execution.
        </p>
      </div>

      <div class="service-card">
        <div class="service-card__head">
          <span class="service-card__number">02</span>
          <span class="service-card__cue">Explore &rarr;</span>
        </div>
        <h3 class="service-card__title">Capital Markets</h3>
        <p class="service-card__body">
          Equity and debt origination across public and private channels. IPOs,
          follow-ons, convertibles, and bespoke structured financings.
        </p>
      </div>

      <div class="service-card">
        <div class="service-card__head">
          <span class="service-card__number">03</span>
          <span class="service-card__cue">Explore &rarr;</span>
        </div>
        <h3 class="service-card__title">Restructuring</h3>
        <p class="service-card__body">
          Liability management, recapitalisations, and Chapter 11 advisory for
          companies, creditors, and stakeholders navigating complexity.
        </p>
      </div>

      <div class="service-card">
        <div class="service-card__head">
          <span class="service-card__number">04</span>
          <span class="service-card__cue">Explore &rarr;</span>
        </div>
        <h3 class="service-card__title">Private Capital</h3>
        <p class="service-card__body">
          Direct access to global pools of private equity, sovereign wealth, and
          family office capital for growth and minority investments.
        </p>
      </div>
    </div>
  </div>
</section>

<!-- ── § 03 Selected Transactions ────────────────────────────────────────── -->
<section class="section" id="transactions">
  <div class="container">
    <div class="section-head">
      <div>
        <div class="eyebrow">&sect; 03 &mdash; Selected Transactions</div>
        <h2 class="section-head__title">A record measured<br><span class="italic-accent">by outcome.</span></h2>
      </div>
      <a class="link-rule" href="#transactions">Full Tombstone Archive &rarr;</a>
    </div>

    <div class="ledger">
      <div class="transaction">
        <div class="transaction__figure">
          <div class="transaction__value">$4.2B</div>
          <div class="eyebrow transaction__sub">Sell-side M&amp;A</div>
        </div>
        <div class="transaction__desc">Advised a European industrial conglomerate on its divestiture to a global strategic acquirer.</div>
        <div class="transaction__sector">Industrials</div>
        <div class="transaction__year">2026</div>
      </div>

      <div class="transaction">
        <div class="transaction__figure">
          <div class="transaction__value">$1.8B</div>
          <div class="eyebrow transaction__sub">Senior Notes</div>
        </div>
        <div class="transaction__desc">Joint bookrunner on inaugural high-yield issuance for a leading specialty chemicals platform.</div>
        <div class="transaction__sector">Chemicals</div>
        <div class="transaction__year">2026</div>
      </div>

      <div class="transaction">
        <div class="transaction__figure">
          <div class="transaction__value">$950M</div>
          <div class="eyebrow transaction__sub">Recapitalisation</div>
        </div>
        <div class="transaction__desc">Lead advisor on out-of-court liability management for a North American consumer brand.</div>
        <div class="transaction__sector">Consumer</div>
        <div class="transaction__year">2025</div>
      </div>

      <div class="transaction">
        <div class="transaction__figure">
          <div class="transaction__value">$2.6B</div>
          <div class="eyebrow transaction__sub">Cross-border M&amp;A</div>
        </div>
        <div class="transaction__desc">Exclusive financial advisor on landmark APAC-EU technology combination.</div>
        <div class="transaction__sector">Technology</div>
        <div class="transaction__year">2025</div>
      </div>
    </div>
  </div>
</section>

<!-- ── § 04 Insights ─────────────────────────────────────────────────────── -->
<section class="section section--band" id="insights">
  <div class="container">
    <div class="grid-12 insights__head">
      <div class="insights__intro">
        <div class="eyebrow">&sect; 04 &mdash; Insights</div>
        <h2 class="insights__title">Notes from<br>the <span class="italic-accent">desk.</span></h2>
      </div>
      <p class="insights__aside">
        Considered perspectives from our partners and research teams on the
        forces shaping global capital markets.
      </p>
    </div>

    <div class="hairline-grid hairline-grid--3">
      <article class="insight-card">
        <div class="insight-card__head">
          <span class="eyebrow">Market Letter</span>
          <span class="insight-card__date">Q2 &middot; 2026</span>
        </div>
        <h3 class="insight-card__title">Rates, Rotation &amp; the Return of Strategic Capital</h3>
        <div class="insight-card__foot">
          <span>12 min read</span>
          <span class="insight-card__cue">Read &rarr;</span>
        </div>
      </article>

      <article class="insight-card">
        <div class="insight-card__head">
          <span class="eyebrow">Sector Note</span>
          <span class="insight-card__date">May 2026</span>
        </div>
        <h3 class="insight-card__title">Energy Transition: Capital Stacks for the Next Decade</h3>
        <div class="insight-card__foot">
          <span>9 min read</span>
          <span class="insight-card__cue">Read &rarr;</span>
        </div>
      </article>

      <article class="insight-card">
        <div class="insight-card__head">
          <span class="eyebrow">Quarterly Review</span>
          <span class="insight-card__date">Q1 &middot; 2026</span>
        </div>
        <h3 class="insight-card__title">Sponsor Activity &amp; the Resurgence of Take-Privates</h3>
        <div class="insight-card__foot">
          <span>15 min read</span>
          <span class="insight-card__cue">Read &rarr;</span>
        </div>
      </article>
    </div>
  </div>
</section>

<!-- ── § 05 Offices ──────────────────────────────────────────────────────── -->
<section class="section on-ink" id="contact">
  <div class="container">
    <div class="grid-12 contact__head">
      <div class="contact__intro">
        <div class="eyebrow">&sect; 05 &mdash; Offices</div>
        <h2 class="section-head__title">A global firm,<br><span class="italic-accent">locally rooted.</span></h2>
      </div>
      <div class="contact__aside">
        <p>
          For new business enquiries, media, or careers, our partners welcome
          direct correspondence.
        </p>
        <a class="contact__email" href="mailto:partners@captal.com">partners@captal.com <span aria-hidden="true">&rarr;</span></a>
      </div>
    </div>

    <div class="hairline-grid hairline-grid--on-ink hairline-grid--3">
      <div class="office-card">
        <div class="office-card__role">Global Headquarters</div>
        <div class="office-card__city">New York</div>
        <div class="office-card__addr">535 Madison Avenue</div>
      </div>
      <div class="office-card">
        <div class="office-card__role">EMEA</div>
        <div class="office-card__city">London</div>
        <div class="office-card__addr">20 Berkeley Square</div>
      </div>
      <div class="office-card">
        <div class="office-card__role">Asia Pacific</div>
        <div class="office-card__city">Hong Kong</div>
        <div class="office-card__addr">Two IFC, Central</div>
      </div>
      <div class="office-card">
        <div class="office-card__role">DACH</div>
        <div class="office-card__city">Frankfurt</div>
        <div class="office-card__addr">Opernturm, Bockenheimer Landstra&szlig;e</div>
      </div>
      <div class="office-card">
        <div class="office-card__role">Wealth &amp; Private Capital</div>
        <div class="office-card__city">Z&uuml;rich</div>
        <div class="office-card__addr">Bahnhofstrasse 45</div>
      </div>
      <div class="office-card">
        <div class="office-card__role">Southeast Asia</div>
        <div class="office-card__city">Singapore</div>
        <div class="office-card__addr">Marina Bay Financial Centre</div>
      </div>
    </div>
  </div>
</section>
