<?php
/**
 * Site footer.
 *
 * GENERATED by wordpress/build.sh from index.html. Edit that file and re-run
 * the script; changes made here are overwritten.
 *
 * @package captal-onepage
 */

if ( ! function_exists( 'elementor_theme_do_location' ) || ! elementor_theme_do_location( 'footer' ) ) :
	?>
{{SITE_FOOTER}}
<?php endif; ?>

<?php wp_footer(); ?>
</body>
</html>
