<?php
/**
 * The Capiital one-page layout: front page through contact.
 *
 * GENERATED by wordpress/build.sh from index.html. Edit that file and re-run
 * the script; changes made here are overwritten.
 *
 * The site header and footer are NOT here — they come from header.php and
 * footer.php so that ordinary pages and Elementor pages share the same chrome.
 *
 * @package captal-onepage
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
{{SECTIONS}}
