#!/usr/bin/env bash
#
# Assemble everything that gets installed or pasted, from the sources at the repository
# root. index.html is the single source of truth for markup, assets/ for the tokens, the
# typefaces, the styles, the behaviour and the three images.
#
# Edit the sources, run this, commit the result. Editing a generated file directly means
# the next run discards the change without saying so.
#
# What it writes:
#   wordpress/capiital/            the Hello Elementor child theme: tokens, fonts, styles, JS
#   dist/capiital-child-theme.zip  the same, ready for Appearance → Themes → Add New → Upload
#   dist/sections/                 the front page as paste-able pieces, markup only
#   dist/sections-grouped/         the same in three pieces
#   dist/capiital-website.html     one self-contained file, nothing loaded from anywhere
#   dist/capiital-website.zip      the site as separate files, for a static host
#
# What it refuses to write: anything that contacts a third party, and any paste-able piece
# carrying a <style> or a <script>. Both have cost this build a working site once already.
#
# Usage:  wordpress/build.sh
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo"

for f in index.html assets/css/tokens.css assets/css/fonts.css assets/css/styles.css assets/js/main.js; do
  [ -f "$f" ] || { echo "build: missing $f" >&2; exit 1; }
done

# ── the child theme ───────────────────────────────────────────────────────────
# The theme is styling and behaviour only. It renders no content: Elementor owns every
# page, which is the whole reason the last theme was replaced.
theme="wordpress/capiital"
rm -rf "$theme/assets" "$theme/fonts"
mkdir -p "$theme/assets/css/tokens" "$theme/assets/js" "$theme/assets/img" "$theme/assets/fonts"

# tokens.css is a concatenation of the parts, so regenerate it rather than trust the copy.
{
  cat <<'HDR'
/* ───────────────────────────────────────────────────────────────────────────────
   Capiital · tokens
   Generated by wordpress/build.sh from assets/css/tokens/*.css. Do not edit this file;
   edit the parts. colors, typography, spacing, elevation and motion are carried verbatim
   from wordpress-elementor-v3-2026-10-06/tokens/, byte for byte, so the design folder stays
   the single master; site.css holds the only two values this site changes.
   ─────────────────────────────────────────────────────────────────────────────── */

HDR
  for part in colors typography spacing elevation motion site; do
    printf '/* ── %s.css ───────────────────────────────────────────────────────────────── */\n' "$part"
    cat "assets/css/tokens/$part.css"
    printf '\n'
  done
} > assets/css/tokens.css

cp assets/css/tokens.css assets/css/fonts.css assets/css/styles.css "$theme/assets/css/"
cp assets/css/tokens/*.css "$theme/assets/css/tokens/"
cp assets/js/main.js "$theme/assets/js/"
cp assets/img/*.jpg assets/img/*.png "$theme/assets/img/"
cp assets/fonts/*.woff2 "$theme/assets/fonts/"

# ── nothing may be fetched from a third party ─────────────────────────────────
# spec/70 and checklist.md both require it, and the legal page's cookie paragraph states
# it as a fact. A single reinstated @import would make that paragraph untrue.
# The pattern requires the `//` of a real URL, so the guard in functions.php — which exists
# precisely to refuse such a request — and the prose explaining it do not trip it.
EXTERNAL='//(fonts\.googleapis\.com|fonts\.gstatic\.com|cdn\.|cdnjs\.|unpkg\.com|ajax\.googleapis\.com)'
if grep -rInE "$EXTERNAL" index.html assets wordpress/capiital >/dev/null 2>&1; then
  echo "build: a third-party request survives in the sources —" >&2
  grep -rInE "$EXTERNAL" index.html assets wordpress/capiital >&2
  exit 1
fi
echo "build: no third-party requests in the sources"

python3 - "$repo" <<'PY'
import base64, mimetypes, os, re, shutil, sys

repo = sys.argv[1]
html = open(os.path.join(repo, 'index.html'), encoding='utf-8').read()


def grab(pattern, closing, label):
    """The span from the first match of `pattern` to the end of the first `closing`."""
    start = re.search(pattern, html)
    if not start:
        sys.exit('build: could not find %s' % label)
    end = re.search(closing, html[start.start():])
    if not end:
        sys.exit('build: could not close %s' % label)
    return html[start.start(): start.start() + end.end()].rstrip()


SECTION_END = r'</section>\s*(?=\n*<!--|\n*</main|\n*<footer|\Z)'

skip = grab(r'<a class="skip-link"', r'</a>', 'the skip link')
header = grab(r'<header class="site-header"[^>]*>', r'</header>', 'the header')
footer = grab(r'<footer class="capiital-part site-footer[^>]*>', r'</footer>', 'the footer')


def section(sid):
    return grab(r'<section class="[^"]*"[^>]*id="%s">' % sid, SECTION_END, '#' + sid)


quote = grab(r'<section class="capiital-part quote-sec[^"]*">', SECTION_END, 'the quote')

front = section('top')
engage = section('services')
learned = section('learned')
cases = section('cases')
people = section('people')
papers = section('papers')

# ── the pieces ────────────────────────────────────────────────────────────────
# Markup only. The tokens, the typefaces, the styles and the behaviour all come from the
# child theme, so no piece carries a <style> or a <script> — WordPress strips the first
# from widget content, and wpautop mangles the second.
#
# Piece 01 carries the skip link, the header and the front page together. The header is
# position:fixed and needs no layout space; in a widget of its own, its Elementor section
# would still occupy some, pushing the hero down and showing a band of page ground through
# the transparent bar.
#
# Piece 03 carries What we learned and the quote together, and must. While the section is
# staged its own bottom padding and the quote's top padding are both zeroed, through
# `#learned.is-staged + .quote-sec` — an adjacent-sibling selector. Split into two widgets
# they stop being siblings, the selector stops matching, and an eggshell strip opens
# between them on release.
PIECES = [
    ('01-header-front.html', 'The skip link, the header and the front page',
     skip + '\n\n' + header + '\n\n' + front),
    ('02-engage.html', 'Where we engage', engage),
    ('03-learned-quote.html', 'What we learned, and the quote — one piece on purpose',
     learned + '\n\n' + quote),
    ('04-cases.html', 'Cases', cases),
    ('05-people.html', 'Who we are', people),
    ('06-papers.html', 'What we think', papers),
    ('07-footer-contact.html', 'How to reach us, and the footer', footer),
]

GROUPED = [
    ('1-header-front.html', 'The skip link, the header and the front page',
     skip + '\n\n' + header + '\n\n' + front),
    ('2-middle.html', 'Everything between the front page and the footer',
     '\n\n'.join([engage, learned, quote, cases, people, papers])),
    ('3-footer-contact.html', 'How to reach us, and the footer', footer),
]


def write_set(folder, pieces, readme):
    out = os.path.join(repo, 'dist', folder)
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    for name, _label, body in pieces:
        if '<style' in body or '<script' in body:
            sys.exit('build: %s carries a <style> or a <script>; both are filtered '
                     'out of widget content' % name)
        open(os.path.join(out, name), 'w', encoding='utf-8').write(body.strip() + '\n')
    open(os.path.join(out, 'README.md'), 'w', encoding='utf-8').write(readme)
    return out


HOW = """\
## Before the first paste

**Install and activate the theme.** `dist/capiital-child-theme.zip`, under
Appearance → Themes → Add New → Upload, with Hello Elementor installed as its parent. The
theme carries the colours, the two typefaces, every style and all of the behaviour.

Nothing below contains any CSS or any JavaScript, and nothing should ever have any added to
it. WordPress strips `<style>` out of widget content; the whole stylesheet disappeared that
way once and the site rendered as unstyled markup. There is no Additional CSS to paste
either — the theme loads it all.

**In Elementor's settings, before building:** Flexbox Container on, Grid Container on,
Google Fonts off, Load Font Awesome off, Disable Default Colours on, Disable Default Fonts
on, content width 1400, container padding 0, default gap 0, border-radius 0 under Theme
Style. Leave every widget's *Motion Effects* empty: the site's own motion is in the theme,
and Elementor's would fight it.

## The pieces

Add an **HTML widget** for each file, in this order, and paste the file whole:

"""

FOOT = """
## Then

- The page template should be **Elementor Canvas**, so the theme wraps nothing around it.
- Check at 1440, 1024 and 390px wide, in both languages, with and without reduced motion.
  `checklist.md` in the design folder is the list to work through.
- The ledger under *What we think* is four fixed rows here. It becomes a Loop Grid of the
  latest four Publication posts when that post type exists, and then it can never disagree
  with the archive.
"""


def readme_for(pieces, title, note):
    lines = ['# %s\n' % title, note, '\n', HOW]
    for i, (name, label, body) in enumerate(pieces, 1):
        lines.append('%d. **`%s`** — %s  \n   %s bytes\n' % (i, name, label, f'{len(body):,}'))
    lines.append(FOOT)
    return ''.join(lines)


write_set('sections', PIECES, readme_for(
    PIECES, 'The front page, piece by piece',
    'Seven pieces, each for one Elementor HTML widget. Two of them are deliberately not '
    'split further, and the reasons are given beside them.\n'))

write_set('sections-grouped', GROUPED, readme_for(
    GROUPED, 'The front page in three pieces',
    'The same page in three widgets rather than seven: fewer things to place, and fewer '
    'seams. Use this one unless a section needs editing on its own.\n'))

print('build: wrote dist/sections (%d pieces) and dist/sections-grouped (%d)'
      % (len(PIECES), len(GROUPED)))

# ── one self-contained file ───────────────────────────────────────────────────
# Everything inlined, the typefaces and the three images included as data URIs, so the
# file opens from disk and still contacts nothing. It is the thing to send someone who
# wants to see the site without a WordPress install.
single = html


def read(rel):
    return open(os.path.join(repo, rel), encoding='utf-8').read()


def data_uri(rel):
    path = os.path.join(repo, rel)
    mime = mimetypes.guess_type(path)[0] or 'application/octet-stream'
    if rel.endswith('.woff2'):
        mime = 'font/woff2'
    with open(path, 'rb') as fh:
        return 'data:%s;base64,%s' % (mime, base64.b64encode(fh.read()).decode('ascii'))


fonts = read('assets/css/fonts.css')
for face in sorted(os.listdir(os.path.join(repo, 'assets/fonts'))):
    fonts = fonts.replace('../fonts/' + face, data_uri('assets/fonts/' + face))

styles = read('assets/css/styles.css')
for img in sorted(os.listdir(os.path.join(repo, 'assets/img'))):
    styles = styles.replace('../img/' + img, data_uri('assets/img/' + img))

bundle = ('<style>\n' + read('assets/css/tokens.css').rstrip() + '\n\n'
          + fonts.rstrip() + '\n\n' + styles.rstrip() + '\n</style>')

single = re.sub(
    r'<link rel="stylesheet" href="assets/css/tokens\.css">\s*'
    r'<link rel="stylesheet" href="assets/css/fonts\.css">\s*'
    r'<link rel="stylesheet" href="assets/css/styles\.css">',
    bundle, single)
single = single.replace('<script src="assets/js/main.js" defer></script>',
                        '<script>\n' + read('assets/js/main.js').rstrip() + '\n</script>')

# Sub-resources only. An <a href> is a link, not a fetch, and tokens.css naming its own
# sources in a comment is neither.
left = re.findall(r'<(?:link|script|img|source|iframe)\b[^>]*\b(?:href|src)="(?!data:)[^"]*"', single)
left += [u for u in re.findall(r'url\(\s*["\']?([^"\')]+)', single) if not u.startswith('data:')]
if left:
    sys.exit('build: the single file still fetches %s' % left[:4])

open(os.path.join(repo, 'dist', 'capiital-website.html'), 'w', encoding='utf-8').write(single)
print('build: wrote dist/capiital-website.html (%.1f KB, nothing external)'
      % (len(single.encode('utf-8')) / 1024))
PY

# ── deterministic archives ────────────────────────────────────────────────────
# A plain `zip -r` stores each file's mtime and walks the directory in filesystem order, so
# an unchanged source produced a byte-different zip on every run — a tracked binary showing
# a spurious diff each time. Fixed mtimes, a sorted entry list and -X make identical inputs
# give identical bytes.
pack() {
  local zip="$1" root="$2"; shift 2
  rm -f "$zip"
  ( cd "$root" && find "$@" -print0 | LC_ALL=C sort -z \
      | xargs -0 touch -t 202001010000.00 )
  ( cd "$root" && find "$@" -type f -print | LC_ALL=C sort | zip -qX "$repo/$zip" -@ )
  echo "build: wrote $zip"
}

mkdir -p dist
pack dist/capiital-child-theme.zip wordpress capiital
pack dist/capiital-sections.zip dist sections
pack dist/capiital-sections-grouped.zip dist sections-grouped
pack dist/capiital-blank-theme.zip wordpress capiital-blank

# The site as separate files, for a plain static host.
staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT
mkdir -p "$staging/site"
cp index.html "$staging/site/"
mkdir -p "$staging/site/assets"
cp -R assets/css assets/js assets/img assets/fonts "$staging/site/assets/"
pack dist/capiital-website.zip "$staging" site

echo "build: done"
