#!/usr/bin/env bash
#
# Regenerate the WordPress theme from the source site at the repository root.
#
# index.html is the single source of truth for markup and the assets/ folder for
# CSS and JS. Edit those, run this, commit the result. Editing the generated
# theme directly means the next run silently discards your changes.
#
# Usage:  wordpress/build.sh

set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
theme="$repo/wordpress/captal-onepage"

command -v python3 >/dev/null || { echo "build: python3 is required" >&2; exit 1; }

mkdir -p "$theme/assets/css" "$theme/assets/js"

python3 - "$repo" "$theme" <<'PY'
import re, sys, os

repo, theme = sys.argv[1], sys.argv[2]
html = open(os.path.join(repo, 'index.html')).read()

# The body markup is everything between <body> and the trailing <script>: the
# head is replaced by wp_head() and the script by wp_enqueue_script().
m = re.search(r'<body>\n(.*)\n<script src=', html, re.S)
if not m:
    sys.exit('build: could not locate the body markup in index.html')
body = m.group(1).rstrip()

template = '''<?php
/**
 * CAP=TAL — one-page site.
 *
 * GENERATED by wordpress/build.sh from index.html at the repository root.
 * Edit that file and re-run the script; changes made here are overwritten.
 *
 * Deliberately does NOT call get_header() / get_footer(): the design ships its
 * own sticky header and its own footer, so pulling in a theme's would render
 * two of each. Everything WordPress needs is hooked in directly below.
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#242a33">
<?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

%s

<?php wp_footer(); ?>
</body>
</html>
''' % body

open(os.path.join(theme, 'index.php'), 'w').write(template)

# tokens.css is copied as-is; styles.css loses its @import because the theme
# enqueues tokens.css as a declared dependency instead.
tokens = open(os.path.join(repo, 'assets/css/tokens.css')).read()
open(os.path.join(theme, 'assets/css/tokens.css'), 'w').write(tokens)

styles = open(os.path.join(repo, 'assets/css/styles.css')).read()
styles = styles.replace('@import url("tokens.css");\n\n', '')
if '@import' in styles:
    sys.exit('build: an @import survived in styles.css — the enqueue order would break')
open(os.path.join(theme, 'assets/css/styles.css'), 'w').write(styles)

for src, dst in (('assets/js/main.js', 'assets/js/main.js'),
                 ('assets/favicon.svg', 'assets/favicon.svg')):
    open(os.path.join(theme, dst), 'w').write(open(os.path.join(repo, src)).read())

print('build: generated index.php (%d bytes) and assets' % len(template))
PY

if command -v php >/dev/null; then
  php -l "$theme/index.php" >/dev/null && php -l "$theme/functions.php" >/dev/null
  echo "build: php syntax ok"
fi

rm -f "$repo/wordpress/captal-onepage.zip"
( cd "$repo/wordpress" && zip -rq captal-onepage.zip captal-onepage -x '*.DS_Store' )
echo "build: wrote wordpress/captal-onepage.zip"
